Repository lotte-team6-onthefarm/OnAndTheFarm-OrderService, pull requests merged in 2022-11, with the labels that each got.

#18 fix: swagger 설정 추가
  src/main/java/com/team6/onandthefarmorderservice/config/SwaggerConfig.java
Labels: fix

#19 feat: 써킷브레이커 구현
  src/main/java/com/team6/onandthefarmorderservice/service/OrderServiceImp.java
Labels: feat

#20 feat : nudge 기능 기본 구현
  src/main/java/com/team6/onandthefarmorderservice/controller/UserOrderController.java
  src/main/java/com/team6/onandthefarmorderservice/dto/OrderDto.java
  src/main/java/com/team6/onandthefarmorderservice/feignclient/SnsServiceClient.java
  src/main/java/com/team6/onandthefarmorderservice/service/OrderServiceImp.java
  src/main/java/com/team6/onandthefarmorderservice/vo/OrderRequest.java
  src/main/java/com/team6/onandthefarmorderservice/vo/feignclient/FeedVo.java
Labels: feat

#21 fix : userOrderController 조회 api post->get으로 수정
  src/main/java/com/team6/onandthefarmorderservice/controller/UserOrderController.java
  src/main/java/com/team6/onandthefarmorderservice/vo/OrderUserRequest.java
Labels: fix

#22 feat: zipkin서버 추가 / TCC 포인트 구현
  build.gradle
  src/main/java/com/team6/onandthefarmorderservice/TCC.java
  src/main/java/com/team6/onandthefarmorderservice/TccRestAdapter.java
  src/main/java/com/team6/onandthefarmorderservice/controller/UserOrderController.java
  src/main/java/com/team6/onandthefarmorderservice/vo/PointOrderRequest.java
Labels: feat

#23 feat: iamport api 사용을 위해 필요한 dto vo 수정
  src/main/java/com/team6/onandthefarmorderservice/TCC.java
  src/main/java/com/team6/onandthefarmorderservice/controller/UserOrderController.java
  src/main/java/com/team6/onandthefarmorderservice/dto/OrderDto.java
  src/main/java/com/team6/onandthefarmorderservice/vo/OrderRequest.java
Labels: feat

#24 feat : admin security 추가
  src/main/java/com/team6/onandthefarmorderservice/config/SecurityConfig.java
  src/main/java/com/team6/onandthefarmorderservice/security/JwtAuthenticationFilter.java
  src/main/java/com/team6/onandthefarmorderservice/security/JwtTokenUtil.java
  src/main/java/com/team6/onandthefarmorderservice/security/Token.java
Labels: feat

#25 fix : securityConfig admin 추가
  src/main/java/com/team6/onandthefarmorderservice/config/SecurityConfig.java
Labels: fix

#26 fix: cors 오류 부분 수정
  src/main/java/com/team6/onandthefarmorderservice/config/SecurityConfig.java
Labels: fix

#27 fix: security 추가 및 feign용 url 수정
  src/main/java/com/team6/onandthefarmorderservice/config/SecurityConfig.java
  src/main/java/com/team6/onandthefarmorderservice/feignclient/CartServiceClient.java
  src/main/java/com/team6/onandthefarmorderservice/feignclient/ProductServiceClient.java
  src/main/java/com/team6/onandthefarmorderservice/feignclient/SnsServiceClient.java
  src/main/java/com/team6/onandthefarmorderservice/feignclient/UserServiceClient.java
  src/main/java/com/team6/onandthefarmorderservice/feignclient/controller/ProductServiceClientController.java
  src/main/java/com/team6/onandthefarmorderservice/feignclient/controller/SnsServiceClientController.java
Labels: fix

#28 fix: feignclient url 수정 및 결제 취소 추가
  src/main/java/com/team6/onandthefarmorderservice/TCC.java
  src/main/java/com/team6/onandthefarmorderservice/controller/UserOrderController.java
  src/main/java/com/team6/onandthefarmorderservice/feignclient/PaymentServiceClient.java
  src/main/java/com/team6/onandthefarmorderservice/vo/feignclient/PaymentVo.java
Labels: feat, fix

#30 fix: 넛지 point 관련 수정(feedid를 받는 것이 아니라 feedNumber로 받음)
  src/main/java/com/team6/onandthefarmorderservice/TCC.java
  src/main/java/com/team6/onandthefarmorderservice/controller/UserOrderController.java
  src/main/java/com/team6/onandthefarmorderservice/service/OrderServiceImp.java
  src/main/java/com/team6/onandthefarmorderservice/vo/PointOrderRequest.java
Labels: fix

#31 feat: kafka sink 구현
  build.gradle
  src/main/java/com/team6/onandthefarmorderservice/TCC.java
  src/main/java/com/team6/onandthefarmorderservice/controller/UserOrderController.java
  src/main/java/com/team6/onandthefarmorderservice/dto/OrderDto.java
  src/main/java/com/team6/onandthefarmorderservice/dto/OrderProductDto.java
  src/main/java/com/team6/onandthefarmorderservice/kafka/KafkaConsumerConfig.java
  src/main/java/com/team6/onandthefarmorderservice/kafka/KafkaProducerConfig.java
  src/main/java/com/team6/onandthefarmorderservice/kafka/OrderChannelAdapter.java
  src/main/java/com/team6/onandthefarmorderservice/kafka/OrderChannelAdapterKafkaImpl.java
  src/main/java/com/team6/onandthefarmorderservice/kafka/vo/Field.java
  src/main/java/com/team6/onandthefarmorderservice/kafka/vo/KafkaOrderDto.java
  src/main/java/com/team6/onandthefarmorderservice/kafka/vo/Payload.java
  src/main/java/com/team6/onandthefarmorderservice/kafka/vo/PayloadOrderProduct.java
  src/main/java/com/team6/onandthefarmorderservice/kafka/vo/Schema.java
  src/main/java/com/team6/onandthefarmorderservice/service/OrderService.java
  src/main/java/com/team6/onandthefarmorderservice/service/OrderServiceImp.java
  src/main/java/com/team6/onandthefarmorderservice/vo/feignclient/ProductVo.java
Labels: feat

#32 feat : orders 상세정보 response의 username 수정
  src/main/java/com/team6/onandthefarmorderservice/service/OrderServiceImp.java
Labels: feat

#33 fix: 날짜 생성에 대한 것을 한국날짜로 수정
  src/main/java/com/team6/onandthefarmorderservice/utils/DateUtils.java
Labels: fix
